# Generated by Django 6.0.1 on 2026-06-27 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_salaryincrement'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salaryincrement',
            unique_together=set(),
        ),
    ]
